### ISSUE TITLE
query_fact function broken as of 2.0.3

### ISSUE THREAD

**Issue by ayohrling** [dalen/puppet-puppetdbquery#76]
Haven't had a chance to track it down yet, but I just got around to updating from 2.0.2 where the fixes for query_fact function were merged in to 2.0.3 and 2.1.0 and I get the following error with my code that was working with 2.0.2

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, undefined method `get' for {:extract=>[:certname, :name, :value]}:Hash

I wanted to open a ticket to remember to track this down. For now I'm locking my Puppetfile to 2.0.2.

**Comment by loosi** [comment]
Im hit by the same effect right now. Strangely i cannot use puppetdbquery via puppet right now at all. Can't get any any version > 2.0 runing on my live system, while my stage/dev systems with exactly same versions still work as expected. Hopefully I'll find the time to debug this any further this weekend.

**Comment by raphink** [comment]
Still seeing this with version 3.0.1 today.
