### ISSUE TITLE
Query_facts not working in PE 2016.4.2

### ISSUE THREAD

**Issue by nicks85** [dalen/puppet-puppetdbquery#100]
Hi ,

I tried to workout one of my module uses query_facts as it was working in the old PE 3.8.3 version however now its not working , giving me error of nil class 
The same works in PE 3.8.3 

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template ganglia/gmetadp.conf.erb:\n  Filepath: /etc/puppetlabs/code/environments/development/modules/ganglia/templates/gmetadp.conf.erb\n  Line: 46\n  Detail: undefined method `[]' for nil:NilClass\n
