### PR TITLE
Rebased version of PR62

### PR DESCRIPTION
**Pull request by danieldreier**
I've rebased @pyther's PR https://github.com/dalen/puppet-puppetdbquery/pull/62 to facilitate a merge because I have a relatively urgent need for the improvements he made.

@pyther: if you'd rather rebase yourself I'd be glad to close this PR, but I figured that it's been a week so you might be busy with other stuff.

### CODE REVIEW

**Comment by danieldreier** [comment]
I've verified that this works on puppet 4.2 with PDB 3, but am getting a `Error 400 on SERVER: undefined method `check_version' for PuppetDB::Connection:Class` error on an older version of puppet and puppetdb, so this may break backwards compatibility without further work. I'll update when I know more.

**Comment by pyther** [comment]
I rebased #62

**Comment by danieldreier** [comment]
awesome! Thanks @pyther.
