### ISSUE TITLE
Getting 404 errors;

### ISSUE THREAD

**Issue by ghstwhl** [dalen/puppet-puppetdbquery#55]
I know this is probably a config issue on my part, but haven't found a solution anywhere else.

I have two puppet servers.  Both built from the Puppet Collection repo (puppet 4).  One of them I installed puppetdb using the "install from packages" instructions, and the other I built from the "install via Puppet  Module" instructions.  In the system built from packages, puppetdbquery works from both the command line and from within manifests.  On the system build from the puppetdb module, with puppetdbquery then installed, I am getting 404 errors from the command line:

$ puppet query nodes 'Package["puppet-agent"]'

Error: PuppetDB query error: [404] Not Found, query: ["in","name",["extract","certname",["select-resources",["and",["=","exported",false],["=","type","Package"],["=","title","puppet-agent"]]]]]
Error: Try 'puppet help query nodes' for usage

and the same manifests that work on system #1 are failing with this error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, undefined method `server' for Puppet::Util::Puppetdb:Module at /etc/puppetlabs/code/environments/production/modules/wwwbayhostingnet/manifests/munin_master.pp:12:17 on node puppet2.bayhosting.net

In the above error, line 12 of the manifest is:

        $munin_nodes = query_nodes('Package["munin-node"]')

I have verified that I am running 1.6.1, and I have not been able to fine any relevant differences in the configuration of the systems.  Do you have any pointers for fixing my config, or am I hitting some weird edge-case bug?

**Comment by Dantonrrc** [comment]
I am having this issue to since upgrading puppetdb to 3.0

**Comment by ghstwhl** [comment]
Dantonrrc - Thanks.  I can't believe I missed that. Even though I installed both systems via the puppetlabs-release-pc1 repo, the system I built by hand is running puppetdb-2.3.5 and the system I used the puppetlabs-puppetdb module to install puppetdb is running puppetdb-3.0.1.

Does anyone know if there are plans to make puppetdbquery compatible with puppetdb 3.x?

**Comment by dalen** [comment]
Yeah, this issue is expected with PuppetDB 3.0. I've setup a PuppetDB 3.0 dev environment, hopefully I can make a preliminary 3.0 compatible version next week. But I'm away a bit on vacation travelling which is slowing it down.

**Comment by ghstwhl** [comment]
Thank you.  I appreciate the update. I hope you are having a fantastic vacation.  :)

**Comment by dalen** [comment]
I was able to finish the port of puppet explorer to the puppetdb 3 api, but didn't have time to port puppetdbquery yet. Now I'm going away travelling until next Thursday, so this might take another two weeks or so before it is fixed.

**Comment by dalen** [comment]
I just pushed version 2.0.0 which should solve this. Sorry for the wait.

**Comment by Vinclame** [comment]
I'm using version 1.6.1 of puppetdbquery. My puppetdb server is running 4.4.0.  puppet client version is 4.10.7. Should be okay... Right?
Still I'm having issues with puppet query nodes 'Package["puppet-agent"]'
Error: PuppetDB query error: [404] Not Found, query: ["in","name",["extract","certname",["select-resources",["and",["=","exported",false],["=","type","Package"],["=","title","puppet-agent"]]]]]
Error: Try 'puppet help query nodes' for usage
Any tips?

Also backuppc server module gives an error:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, undefined method `server' for Puppet::Util::Puppetdb:Module at /etc/puppetlabs/code/environments/internlnet/modules/backuppc/manifests/server.pp:476:14

**Comment by Vinclame** [comment]
Forget it. I use backuppc which has a hard dependency on puppetdbquery version 1.6.1. Everythings works fine after upgrading to version 2.3.0.
