### ISSUE TITLE
Seems to be broken with puppet 3.0.0-rc5

### ISSUE THREAD

**Issue by csschwe** [dalen/puppet-puppetdbquery#6]
I am working on troubleshooting why I cant get puppetdbquery working with puppet 3.0.0-rc5.  I am getting the following error message.

err: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `start' for #Puppet::Network::HTTP::Connection:0x7fa6e25db7c8

I will continue to try and figure this out, but any help or pointers would be very nice.

Thanks,
